/*
 * Copyright (c) 2024, Qorvo Inc
 *
 * This software is owned by Qorvo Inc
 * and protected under applicable copyright laws.
 * It is delivered under the terms of the license
 * and is intended and supplied for use solely and
 * exclusively with products manufactured by
 * Qorvo Inc.
 *
 *
 * THIS SOFTWARE IS PROVIDED IN AN "AS IS"
 * CONDITION. NO WARRANTIES, WHETHER EXPRESS,
 * IMPLIED OR STATUTORY, INCLUDING, BUT NOT
 * LIMITED TO, IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.
 * QORVO INC. SHALL NOT, IN ANY
 * CIRCUMSTANCES, BE LIABLE FOR SPECIAL,
 * INCIDENTAL OR CONSEQUENTIAL DAMAGES,
 * FOR ANY REASON WHATSOEVER.
 *
 *
 */

#ifndef _Q_DRV_AKUMA_TRIGGERS_H_
#define _Q_DRV_AKUMA_TRIGGERS_H_

/**
 * @defgroup Q_DRV_AKUMA_TRIGGERS Akuma triggers driver
 * @{
 *
 * @brief This is a driver for QUIC akuma triggers that are generated by the akuma block.
 *
 * @file qDrvAkumaTriggers.h
 *
 */

/*****************************************************************************
 *                    Includes Definitions
 *****************************************************************************/

#include "qDrvCommon.h"

#if defined(REG_QUIC_PRESENT)
#include "qDrvQUICInternal.h"
#endif /* defined(REG_QUIC_PRESENT) */

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 *                    Type Definitions
 *****************************************************************************/

/** @enum qDrvAkumaTriggers_QuicSrcTrigger_t */
//@{
#define qDrvAkumaTriggers_QuicSrcTriggerIpcChannel 0
#define qDrvAkumaTriggers_QuicSrcTriggerPaOn       1
#define qDrvAkumaTriggers_QuicSrcTriggerPhyRx      2
#define qDrvAkumaTriggers_QuicSrcTriggerPhyTx      3
#define qDrvAkumaTriggers_QuicSrcTriggerRxOn       4
#define qDrvAkumaTriggers_QuicSrcTriggerTxOn       5
/** @typedef qDrvAkumaTriggers_QuicSrcTrigger_t
 *  @brief Akuma Triggers Quic source trigger.
 */
typedef UInt8 qDrvAkumaTriggers_QuicSrcTrigger_t;
//@}

#if defined(REG_QUIC_PRESENT)
/** @brief Akuma QUIC trigger configuration structure. */
typedef struct {
    qDrvAkumaTriggers_QuicSrcTrigger_t srcTrigger; /**< Required source trigger. */
    UInt8 ipcChannel;                              /**< QUIC channel.*/
    Q_DRV_QUIC_INTERNAL_TRIGGER_FIELD(); /**< Required trigger field. */
} qDrvAkumaTriggers_QuicTriggerConfig_t;
#endif                                   /* REG_QUIC_PRESENT */

/** @brief Akuma Triggers instance structure. */
typedef struct {
#if defined(REG_QUIC_PRESENT)
    qDrvQUIC_Internal_t* quicApi; /**< QUIC API pointer implementation. */
#endif                            /* REG_QUIC_PRESENT */
} qDrvAkumaTriggers_t;

/**
 * @brief Initializes the state variables for the Akuma Triggers driver.
 *
 * @param[in] pInstance   Pointer to the Akuma triggers instance.
 *
 * @retval Q_OK           Success.
 * @retval Q_ERR_INVSTATE Instance is already initialized.
 */
qResult_t qDrvAkumaTriggers_Init(qDrvAkumaTriggers_t* const pInstance);

/**
 * @brief Deinitialize the Akuma Triggers instance.
 *
 * @param[in] pInstance Pointer to the Akuma triggers instance.
 *
 * @retval Q_OK Success.
 */
qResult_t qDrvAkumaTriggers_Deinit(qDrvAkumaTriggers_t* const pInstance);

#ifdef __cplusplus
}
#endif

/** @} */

#endif // _Q_DRV_AKUMA_TRIGGERS_H_
