/*
 * Copyright (c) 2014-2016, GreenPeak Technologies
 * Copyright (c) 2017, Qorvo Inc
 *
 * This software is owned by Qorvo Inc
 * and protected under applicable copyright laws.
 * It is delivered under the terms of the license
 * and is intended and supplied for use solely and
 * exclusively with products manufactured by
 * Qorvo Inc.
 *
 *
 * THIS SOFTWARE IS PROVIDED IN AN "AS IS"
 * CONDITION. NO WARRANTIES, WHETHER EXPRESS,
 * IMPLIED OR STATUTORY, INCLUDING, BUT NOT
 * LIMITED TO, IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.
 * QORVO INC. SHALL NOT, IN ANY
 * CIRCUMSTANCES, BE LIABLE FOR SPECIAL,
 * INCIDENTAL OR CONSEQUENTIAL DAMAGES,
 * FOR ANY REASON WHATSOEVER.
 *
 *
 */

#ifndef _GPHAL_RADIO_INTERRUPTS_MASKS_CHECKS_H_
#define _GPHAL_RADIO_INTERRUPTS_MASKS_CHECKS_H_

/*****************************************************************************
 *                    Includes Definitions
 *****************************************************************************/

#include "gpHal.h"

/*****************************************************************************
 *                    Macro Definitions
 *****************************************************************************/

#define GPHAL_RCI_MASK_OFFSET   GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_IND_INTERRUPT_LSB


// Check the order of the interrupt masks - the code will construct the global unmasked field in this same order - so we want to get notified if this changes
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_A_INTERRUPT_LSB                  == 0);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_B_INTERRUPT_LSB                  == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_A_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_C_INTERRUPT_LSB                  == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_B_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_D_INTERRUPT_LSB                  == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_C_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_CMD_PROCESSED_INTERRUPT_LSB           == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_D_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_ERROR_INTERRUPT_LSB                   == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_CMD_PROCESSED_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_UNEXPECTED_COND_INTERRUPT_LSB         == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_ERROR_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_STAT_INTERRUPT_LSB                    == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_UNEXPECTED_COND_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_ADV_TX_INTERRUPT_LSB                  == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_STAT_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SCAN_REQ_RX_INTERRUPT_LSB             == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_ADV_TX_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SCAN_RSP_TX_INTERRUPT_LSB             == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SCAN_REQ_RX_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SCAN_REQ_TX_INTERRUPT_LSB             == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SCAN_RSP_TX_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_CONN_REQ_TX_INTERRUPT_LSB             == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SCAN_REQ_TX_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SUBEV_DONE_INTERRUPT_LSB              == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_CONN_REQ_TX_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_EVENT_PROCESSED_INTERRUPT_LSB         == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SUBEV_DONE_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_LAST_CONN_EVENT_CNT_INTERRUPT_LSB     == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_EVENT_PROCESSED_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_EVENT_SKIPPED_INTERRUPT_LSB           == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_LAST_CONN_EVENT_CNT_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_IND_INTERRUPT_LSB            == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_EVENT_SKIPPED_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_0_INTERRUPT_LSB          == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_IND_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_1_INTERRUPT_LSB          == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_0_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_2_INTERRUPT_LSB          == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_1_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_3_INTERRUPT_LSB          == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_2_INTERRUPT_LSB  + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_DATA_IND_INTERRUPT_LSB        == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_3_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_ADV_IND_INTERRUPT_LSB         == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_DATA_IND_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_CONN_REQ_IND_INTERRUPT_LSB    == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_ADV_IND_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_CONN_RSP_IND_INTERRUPT_LSB    == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_CONN_REQ_IND_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_DATA_CNF_INTERRUPT_LSB        == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_CONN_RSP_IND_INTERRUPT_LSB + 1);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RX_PTR_LIST_EMPTY_INTERRUPT_LSB       == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_DATA_CNF_INTERRUPT_LSB + 1);

// Check that IPC related registers are matching
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_A_INTERRUPT_LSB                  == GP_WB_AK_IPC_UNMASKED_RT2X_FLAG_A_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_B_INTERRUPT_LSB                  == GP_WB_AK_IPC_UNMASKED_RT2X_FLAG_B_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_C_INTERRUPT_LSB                  == GP_WB_AK_IPC_UNMASKED_RT2X_FLAG_C_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_FLAG_D_INTERRUPT_LSB                  == GP_WB_AK_IPC_UNMASKED_RT2X_FLAG_D_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_CMD_PROCESSED_INTERRUPT_LSB           == GP_WB_AK_IPC_UNMASKED_RT2X_CMD_PROCESSED_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_ERROR_INTERRUPT_LSB                   == GP_WB_AK_IPC_UNMASKED_RT2X_ERROR_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_UNEXPECTED_COND_INTERRUPT_LSB         == GP_WB_AK_IPC_UNMASKED_RT2X_UNEXPECTED_COND_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_STAT_INTERRUPT_LSB                    == GP_WB_AK_IPC_UNMASKED_RT2X_STAT_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_ADV_TX_INTERRUPT_LSB                  == GP_WB_AK_IPC_UNMASKED_RT2X_ADV_TX_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SCAN_REQ_RX_INTERRUPT_LSB             == GP_WB_AK_IPC_UNMASKED_RT2X_SCAN_REQ_RX_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SCAN_RSP_TX_INTERRUPT_LSB             == GP_WB_AK_IPC_UNMASKED_RT2X_SCAN_RSP_TX_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SCAN_REQ_TX_INTERRUPT_LSB             == GP_WB_AK_IPC_UNMASKED_RT2X_SCAN_REQ_TX_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_CONN_REQ_TX_INTERRUPT_LSB             == GP_WB_AK_IPC_UNMASKED_RT2X_CONN_REQ_TX_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_SUBEV_DONE_INTERRUPT_LSB              == GP_WB_AK_IPC_UNMASKED_RT2X_SUBEV_DONE_INTERRUPT_LSB);
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_EVENT_PROCESSED_INTERRUPT_LSB         == GP_WB_AK_INT_CTRL_MASKED_IPCRT2X_EVENT_PROCESSED_INTERRUPT_LSB);
// This is the start of the RCI fields - check if their order is the same as well
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_IND_INTERRUPT_LSB            == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_DATA_IND_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_0_INTERRUPT_LSB          == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_DATA_CNF_0_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_1_INTERRUPT_LSB          == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_DATA_CNF_1_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_2_INTERRUPT_LSB          == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_DATA_CNF_2_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_DATA_CNF_3_INTERRUPT_LSB          == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_DATA_CNF_3_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_DATA_IND_INTERRUPT_LSB        == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_BLE_DATA_IND_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_ADV_IND_INTERRUPT_LSB         == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_BLE_ADV_IND_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_CONN_REQ_IND_INTERRUPT_LSB    == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_BLE_CONN_REQ_IND_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_CONN_RSP_IND_INTERRUPT_LSB    == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_BLE_CONN_RSP_IND_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_DATA_CNF_INTERRUPT_LSB        == (GPHAL_RCI_MASK_OFFSET + GP_WB_AK_IPC_UNMASKED_RT2X_RCI_BLE_DATA_CNF_INTERRUPT_LSB));
GP_COMPILE_TIME_VERIFY(GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RX_PTR_LIST_EMPTY_INTERRUPT_LSB       == GP_WB_AK_INT_CTRL_MASK_IPCRT2X_RCI_BLE_DATA_CNF_INTERRUPT_LSB + 1);

#endif //_GPHAL_RADIO_INTERRUPTS_MASKS_CHECKS_H_
