/*
 * Copyright (c) 2022, Qorvo Inc
 *
 * !!! This is a generated file. !!!
 *
 * This software is owned by Qorvo Inc
 * and protected under applicable copyright laws.
 * It is delivered under the terms of the license
 * and is intended and supplied for use solely and
 * exclusively with products manufactured by
 * Qorvo Inc.
 *
 * THIS SOFTWARE IS PROVIDED IN AN "AS IS"
 * CONDITION. NO WARRANTIES, WHETHER EXPRESS,
 * IMPLIED OR STATUTORY, INCLUDING, BUT NOT
 * LIMITED TO, IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.
 * QORVO INC. SHALL NOT, IN ANY
 * CIRCUMSTANCES, BE LIABLE FOR SPECIAL,
 * INCIDENTAL OR CONSEQUENTIAL DAMAGES,
 * FOR ANY REASON WHATSOEVER.
 *
 *
 */

#include "gpHal.h"
#if defined(GP_DIVERSITY_REGMAPS_IN_HAL_PLATFORM)
#include "hal.h"
#endif //defined(GP_DIVERSITY_REGMAPS_IN_HAL_PLATFORM)

/*****************************************************************************
 *                    Macro Definitions
 *****************************************************************************/

#define GP_COMPONENT_ID GP_COMPONENT_ID_GPHAL

//wrappers/stubs for RAP code
#define abs(a)              (((a) < 0) ? -(a) : (a))

/*****************************************************************************
 *                    Public Function Definitions
 *****************************************************************************/

/*
 * The actual RAP methods.
 */




void ak_rap_rx_adc_set_sample_rate(Bool sample_rate_32M)
{
    if (sample_rate_32M)
    {
        GP_WB_WRITE_AK_RX_RXNB_ADC_SAMPLE_RATE_SEL(0);
        GP_WB_WRITE_AK_RX_RXNB_BBGM_HIGH_CUR_MODE(1);
        GP_WB_WRITE_AK_RX_CIC_D32_ENA(1);
    }
    else
    {
        GP_WB_WRITE_AK_RX_RXNB_ADC_SAMPLE_RATE_SEL(1);
        GP_WB_WRITE_AK_RX_RXNB_BBGM_HIGH_CUR_MODE(0);
        GP_WB_WRITE_AK_RX_CIC_D32_ENA(0);
    }
}


void ak_rap_rx_if_set_mode(Bool zif_not_lif)
{

    if (zif_not_lif)
    {
        ak_rap_rx_adc_set_sample_rate(false);
        GP_WB_WRITE_AK_CAL_MGR_ZB_LOW_AAF_BW_RX0(1);
        GP_WB_WRITE_AK_CAL_MGR_BLE_LOW_AAF_BW_RX0(1);
        GP_WB_WRITE_AK_CAL_MGR_BLE_HDR_LOW_AAF_BW_RX0(1);
        GP_WB_WRITE_AK_CAL_MGR_BLE_LR_LOW_AAF_BW_RX0(1);
        GP_WB_WRITE_AK_CAL_MGR_ZB_LOW_AAF_BW_RX1(1);
        GP_WB_WRITE_AK_CAL_MGR_BLE_LOW_AAF_BW_RX1(1);
        GP_WB_WRITE_AK_CAL_MGR_BLE_HDR_LOW_AAF_BW_RX1(1);
        GP_WB_WRITE_AK_CAL_MGR_BLE_LR_LOW_AAF_BW_RX1(1);
        GP_WB_WRITE_AK_RX_DOWNMIX_FREQ0(0);
        GP_WB_WRITE_AK_RX_DOWNMIX_FREQ1(0);
        GP_WB_WRITE_AK_RX_DOWNMIX_ENA(0);
        GP_WB_WRITE_AK_RX_NOTCH_ENA(0);
        GP_WB_WRITE_AK_RX_EQU_ENA(0);
        GP_WB_WRITE_AK_RX_ALGORITHM_LIF(0);
        GP_WB_WRITE_AK_RX_BBSETTLE_LONG0(17);
        GP_WB_WRITE_AK_RX_BBSETTLE_LONG1(7);
        GP_WB_WRITE_AK_RX_BBSETTLE_SHORT(8);
        GP_WB_WRITE_AK_RX_MAX_RSSI_NB_0(980);
        GP_WB_WRITE_AK_RX_MAX_RSSI_WB_0(980);
        GP_WB_WRITE_AK_RX_MAX_RSSI_NB_1(980);
        GP_WB_WRITE_AK_RX_MAX_RSSI_WB_1(980);
    }
    else
    {
        ak_rap_rx_adc_set_sample_rate(true);
        GP_WB_WRITE_AK_CAL_MGR_ZB_LOW_AAF_BW_RX0(0);
        GP_WB_WRITE_AK_CAL_MGR_BLE_LOW_AAF_BW_RX0(1);
        GP_WB_WRITE_AK_CAL_MGR_BLE_HDR_LOW_AAF_BW_RX0(0);
        GP_WB_WRITE_AK_CAL_MGR_BLE_LR_LOW_AAF_BW_RX0(1);
        GP_WB_WRITE_AK_CAL_MGR_ZB_LOW_AAF_BW_RX1(0);
        GP_WB_WRITE_AK_CAL_MGR_BLE_LOW_AAF_BW_RX1(1);
        GP_WB_WRITE_AK_CAL_MGR_BLE_HDR_LOW_AAF_BW_RX1(0);
        GP_WB_WRITE_AK_CAL_MGR_BLE_LR_LOW_AAF_BW_RX1(1);
        GP_WB_WRITE_AK_RX_DOWNMIX_FREQ0(16);
        GP_WB_WRITE_AK_RX_DOWNMIX_FREQ1(24);
        GP_WB_WRITE_AK_RX_DOWNMIX_ENA(1);
        GP_WB_WRITE_AK_RX_NOTCH_ENA(1);
        GP_WB_WRITE_AK_RX_EQU_ENA(1);
        GP_WB_WRITE_AK_RX_ALGORITHM_LIF(1);
        GP_WB_WRITE_AK_RX_BBSETTLE_LONG0(12);
        GP_WB_WRITE_AK_RX_BBSETTLE_LONG1(7);
        GP_WB_WRITE_AK_RX_BBSETTLE_SHORT(2);
        GP_WB_WRITE_AK_RX_MAX_RSSI_NB_0(1048);
        GP_WB_WRITE_AK_RX_MAX_RSSI_WB_0(1048);
        GP_WB_WRITE_AK_RX_MAX_RSSI_NB_1(1048);
        GP_WB_WRITE_AK_RX_MAX_RSSI_WB_1(1048);
    }

}

void ak_rap_rx_zb_set_mode(UInt8 rx_mode)
{

    switch (rx_mode)
    {


        case RAP_RX_MODE_N_A0:
        case RAP_RX_MODE_N_A1:
        case RAP_RX_MODE_N_DF:
        case RAP_RX_MODE_NS_A0:
        case RAP_RX_MODE_NS_A1:
        case RAP_RX_MODE_NS_DF:
        case RAP_RX_MODE_O_A0:
        case RAP_RX_MODE_O_A1:
        case RAP_RX_MODE_O_DF:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_ZB(GP_WB_ENUM_AK_ZB_RECEIVER_MODE_MCH);

            GP_WB_WRITE_AK_PLME_FORCE_CHANNEL_TRANSITION_ON_EACH_SLOT(0);
            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_LP(17);
            GP_WB_WRITE_AK_RX_USE_LONG_PREAMBLE_EVAL(1);
            GP_WB_WRITE_AK_PLME_ENABLE_CHANNEL_DISABLE_FEATURE(0);
            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(0);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);

            break;
        }
        case RAP_RX_MODE_N_AD:
        case RAP_RX_MODE_NS_AD:
        case RAP_RX_MODE_O_AD:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_ZB(GP_WB_ENUM_AK_ZB_RECEIVER_MODE_MCH_AD);

            GP_WB_WRITE_AK_PLME_FORCE_CHANNEL_TRANSITION_ON_EACH_SLOT(0);
            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_LP(17);
            GP_WB_WRITE_AK_RX_WAIT_SECOND_ANTENNA(1);
            GP_WB_WRITE_AK_RX_USE_LONG_PREAMBLE_EVAL(1);
            GP_WB_WRITE_AK_PLME_ENABLE_CHANNEL_DISABLE_FEATURE(0);
            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);


            break;
        }
        case RAP_RX_MODE_L_A0:
        case RAP_RX_MODE_L_A1:
        case RAP_RX_MODE_L_DF:
        case RAP_RX_MODE_LS_A0:
        case RAP_RX_MODE_LS_A1:
        case RAP_RX_MODE_LS_DF:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_ZB(GP_WB_ENUM_AK_ZB_RECEIVER_MODE_LPL);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_LP(17);
            GP_WB_WRITE_AK_RX_USE_LONG_PREAMBLE_EVAL(0);
            GP_WB_WRITE_AK_PLME_ENABLE_CHANNEL_DISABLE_FEATURE(0);
            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);

            break;
        }
        case RAP_RX_MODE_L_AD:
        case RAP_RX_MODE_LS_AD:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_ZB(GP_WB_ENUM_AK_ZB_RECEIVER_MODE_LPL_AD);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_LP(17);
            GP_WB_WRITE_AK_RX_WAIT_SECOND_ANTENNA(1);
            GP_WB_WRITE_AK_RX_USE_LONG_PREAMBLE_EVAL(0);
            GP_WB_WRITE_AK_PLME_ENABLE_CHANNEL_DISABLE_FEATURE(0);
            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);


            break;
        }
        case RAP_RX_MODE_M_A0:
        case RAP_RX_MODE_M_A1:
        case RAP_RX_MODE_M_DF:
        case RAP_RX_MODE_MB_A0:
        case RAP_RX_MODE_MB_A1:
        case RAP_RX_MODE_MB_DF:
        case RAP_RX_MODE_MBR_A0:
        case RAP_RX_MODE_MBR_A1:
        case RAP_RX_MODE_MBR_DF:
        case RAP_RX_MODE_S_A0:
        case RAP_RX_MODE_S_A1:
        case RAP_RX_MODE_S_DF:
        case RAP_RX_MODE_MS_A0:
        case RAP_RX_MODE_MS_A1:
        case RAP_RX_MODE_MS_DF:
        case RAP_RX_MODE_MSB_A0:
        case RAP_RX_MODE_MSB_A1:
        case RAP_RX_MODE_MSB_DF:
        case RAP_RX_MODE_MSBR_A0:
        case RAP_RX_MODE_MSBR_A1:
        case RAP_RX_MODE_MSBR_DF:
        case RAP_RX_MODE_MBXZB:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_ZB(GP_WB_ENUM_AK_ZB_RECEIVER_MODE_MCH);

            GP_WB_WRITE_AK_PLME_FORCE_CHANNEL_TRANSITION_ON_EACH_SLOT(1);
            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_LP(15);
            GP_WB_WRITE_AK_PLME_ENABLE_CHANNEL_DISABLE_FEATURE(1);
            GP_WB_WRITE_AK_RX_USE_LONG_PREAMBLE_EVAL(0);
            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);
            GP_WB_WRITE_AK_RX_EARLY_CH_CHANGE_AFTER_VAL_FAIL_EN(1);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);

            break;
        }
        case RAP_RX_MODE_M_AD:
        case RAP_RX_MODE_MS_AD:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_ZB(GP_WB_ENUM_AK_ZB_RECEIVER_MODE_MCH_AD);

            GP_WB_WRITE_AK_PLME_FORCE_CHANNEL_TRANSITION_ON_EACH_SLOT(1);
            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_LP(17);
            GP_WB_WRITE_AK_RX_WAIT_SECOND_ANTENNA(0);
            GP_WB_WRITE_AK_RX_USE_LONG_PREAMBLE_EVAL(0);
            GP_WB_WRITE_AK_PLME_ENABLE_CHANNEL_DISABLE_FEATURE(1);
            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);
            GP_WB_WRITE_AK_RX_EARLY_CH_CHANGE_AFTER_VAL_FAIL_EN(1);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);


            break;
        }
        default:
        {

            break;
        }
    }


}


void ak_rap_rx_ble_set_mode(UInt8 rx_mode)
{

    switch (rx_mode)
    {


        case RAP_RX_MODE_B_A0:
        case RAP_RX_MODE_B_A1:
        case RAP_RX_MODE_B_DF:
        case RAP_RX_MODE_B_AD:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_BLE(GP_WB_ENUM_AK_BLE_RECEIVER_MODE_BLE);

            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE(1);
            GP_WB_WRITE_AK_RX_BT_EXP_DELAY(32);

            GP_WB_WRITE_AK_RX_BT_TIMEOUT_QUARD_TIMER(9);

            GP_WB_WRITE_AK_RX_BT_I_ONLY_EN(1);
            GP_WB_WRITE_AK_RX_BT_I_ONLY_BUF_EN(1);


            GP_WB_WRITE_AK_RX_BT_CLR_MAG_SR_ON_PIP(1);
            GP_WB_WRITE_AK_RX_RSSI_HOLD_UPON_TRAINING_RST(1);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_LONG(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_PIP(255);
            GP_WB_WRITE_AK_RX_RSSI_CLEAR_ON_LR_CYC_DET(1);

            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);

            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_BLE_TIMEOUT(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);
            GP_WB_WRITE_AK_RX_BT_PIP_PSEUDO_MAKS_ALWAYS_EN(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);

            GP_WB_WRITE_AK_RX_BT_FAST_VALIDATION(1);
            GP_WB_WRITE_AK_RX_BT_2M_DIRECT_I_DELAY(0);
            GP_WB_WRITE_AK_RX_BT_2M_VALIDATION_START_TUNE(-1);
            GP_WB_WRITE_AK_RX_BT_IQ_BUFFER_DEPTH_CORR(-1);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_BT(150);


            break;
        }
        case RAP_RX_MODE_H_A0:
        case RAP_RX_MODE_H_A1:
        case RAP_RX_MODE_H_DF:
        case RAP_RX_MODE_H_AD:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_BLE(GP_WB_ENUM_AK_BLE_RECEIVER_MODE_BLE_HDR);

            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE_HDR(1);
            GP_WB_WRITE_AK_RX_BT_EXP_DELAY(64);
            GP_WB_WRITE_AK_RX_BT_2M_BIAS_GAIN(2);
            GP_WB_WRITE_AK_RX_BT_2M_LP_INIT_STATE_IDX_OVERRULE_EN(0);
            GP_WB_WRITE_AK_RX_BT_2M_LAST_RX_BYTES_LEV(0);

            GP_WB_WRITE_AK_RX_BT_2M_RSSI_HOLD_UPON_TRAINING_RST(0);
            GP_WB_WRITE_AK_RX_BT_2M_CLR_MAG_SR_ON_PIP(0);

            GP_WB_WRITE_AK_RX_BT_2M_DATA_VALID_ENABLE(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);


            GP_WB_WRITE_AK_RX_BT_I_ONLY_EN(1);
            GP_WB_WRITE_AK_RX_BT_I_ONLY_BUF_EN(1);



            GP_WB_WRITE_AK_RX_RSSI_CLEAR_ON_LR_CYC_DET(1);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_LONG(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_PIP(255);
            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);
            GP_WB_WRITE_AK_RX_SFSK_EN(0);

            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_BLE_TIMEOUT(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);
            GP_WB_WRITE_AK_RX_BT_PIP_PSEUDO_MAKS_ALWAYS_EN(0);

            GP_WB_WRITE_AK_RX_BT_FAST_VALIDATION(1);
            GP_WB_WRITE_AK_RX_BT_2M_DIRECT_I_DELAY(1);
            GP_WB_WRITE_AK_RX_BT_2M_VALIDATION_START_TUNE(-3);
            GP_WB_WRITE_AK_RX_BT_IQ_BUFFER_DEPTH_CORR(0);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_BT(203);


            break;
        }
        case RAP_RX_MODE_R_A0:
        case RAP_RX_MODE_R_A1:
        case RAP_RX_MODE_R_DF:
        case RAP_RX_MODE_R_AD:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_BLE(GP_WB_ENUM_AK_BLE_RECEIVER_MODE_BLE_LR);

            GP_WB_WRITE_AK_RX_BT_TIMEOUT_QUARD_TIMER(21);
            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE(0);

            GP_WB_WRITE_AK_RX_BT_I_ONLY_EN(1);
            GP_WB_WRITE_AK_RX_BT_I_ONLY_BUF_EN(1);


            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(1);
            GP_WB_WRITE_AK_RX_BT_LR_RESTART_ON_PIP_EN(1);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE(1);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_LONG(1);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_PIP(1);

            GP_WB_WRITE_AK_RX_LAST_RX_BYTES_LR_LEV(9);
            GP_WB_WRITE_AK_RX_BT_PIP_PSEUDO_MAKS_ALWAYS_EN(1);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(3);

            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_BLE_TIMEOUT(0);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(0);

            GP_WB_WRITE_AK_RX_RSSI_CLEAR_ON_LR_CYC_DET(1);
            GP_WB_WRITE_AK_RX_BT_LR_RSSI_DET_PSEUDO_DIS_LEN(0);
            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);

            GP_WB_WRITE_AK_RX_BT_FAST_VALIDATION(0);
            GP_WB_WRITE_AK_RX_BT_2M_DIRECT_I_DELAY(0);
            GP_WB_WRITE_AK_RX_BT_2M_VALIDATION_START_TUNE(-1);
            GP_WB_WRITE_AK_RX_BT_IQ_BUFFER_DEPTH_CORR(0);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_BT(203);


            break;
        }
        case RAP_RX_MODE_BR_A0:
        case RAP_RX_MODE_BR_A1:
        case RAP_RX_MODE_BR_DF:
        case RAP_RX_MODE_BR_AD:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_BLE(GP_WB_ENUM_AK_BLE_RECEIVER_MODE_BLE_CONCURRENT);

            GP_WB_WRITE_AK_RX_BT_TIMEOUT_QUARD_TIMER(21);

            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE(1);
            GP_WB_WRITE_AK_RX_BT_EXP_DELAY(32);


            GP_WB_WRITE_AK_RX_BT_LR_RESTART_ON_PIP_EN(1);

            GP_WB_WRITE_AK_RX_BT_CLR_MAG_SR_ON_PIP(1);
            GP_WB_WRITE_AK_RX_BT_LR_RSSI_DET_PSEUDO_DIS_LEN(38);


            GP_WB_WRITE_AK_RX_LAST_RX_BYTES_LR_LEV(9);
            GP_WB_WRITE_AK_RX_BT_PIP_PSEUDO_MAKS_ALWAYS_EN(1);
            GP_WB_WRITE_AK_RX_RSSI_CLEAR_ON_LR_CYC_DET(0);

            GP_WB_WRITE_AK_RX_LAST_RX_BYTES_LEV(0);
            GP_WB_WRITE_AK_RX_RSSI_HOLD_UPON_TRAINING_RST(1);

            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(3);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);

            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_LONG(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_PIP(255);

            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_BLE_TIMEOUT(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);
            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(0);

            GP_WB_WRITE_AK_RX_BT_FAST_VALIDATION(0);
            GP_WB_WRITE_AK_RX_BT_2M_DIRECT_I_DELAY(0);
            GP_WB_WRITE_AK_RX_BT_2M_VALIDATION_START_TUNE(-1);
            GP_WB_WRITE_AK_RX_BT_IQ_BUFFER_DEPTH_CORR(0);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_BT(203);


            break;
        }
        case RAP_RX_MODE_MB_A0:
        case RAP_RX_MODE_MB_A1:
        case RAP_RX_MODE_MB_DF:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_BLE(GP_WB_ENUM_AK_BLE_RECEIVER_MODE_BLE);
            GP_WB_WRITE_AK_RX_BT_LR_MBR_EN(0);

            GP_WB_WRITE_AK_RX_HOLD_BLE_TIMEOUT_COUNTER_EN(0);
            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE(1);

            GP_WB_WRITE_AK_RX_BT_TIMEOUT_QUARD_TIMER(9);

            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(1);

            GP_WB_WRITE_AK_RX_RSSI_CLEAR_ON_LR_CYC_DET(1);

            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_BLE_TIMEOUT(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);

            GP_WB_WRITE_AK_RX_BT_CLR_MAG_SR_ON_PIP(0);
            GP_WB_WRITE_AK_RX_BT_PIP_PSEUDO_MAKS_ALWAYS_EN(0);
            GP_WB_WRITE_AK_RX_RSSI_HOLD_UPON_TRAINING_RST(0);
            GP_WB_WRITE_AK_RX_EARLY_CH_CHANGE_AFTER_VAL_FAIL_EN(1);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_LONG(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_PIP(255);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);

            GP_WB_WRITE_AK_RX_BT_FAST_VALIDATION(0);
            GP_WB_WRITE_AK_RX_BT_2M_DIRECT_I_DELAY(0);
            GP_WB_WRITE_AK_RX_BT_2M_VALIDATION_START_TUNE(-1);
            GP_WB_WRITE_AK_RX_BT_IQ_BUFFER_DEPTH_CORR(0);

            GP_WB_WRITE_AK_RX_FAIL_TIMEOUT_VALUE(40);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_BT(203);


            break;
        }
        case RAP_RX_MODE_MBR_A0:
        case RAP_RX_MODE_MBR_A1:
        case RAP_RX_MODE_MBR_DF:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_BLE(GP_WB_ENUM_AK_BLE_RECEIVER_MODE_BLE_CONCURRENT);
            GP_WB_WRITE_AK_RX_BT_LR_MBR_EN(1);

            GP_WB_WRITE_AK_RX_HOLD_BLE_TIMEOUT_COUNTER_EN(1);
            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE(1);

            GP_WB_WRITE_AK_RX_BT_TIMEOUT_QUARD_TIMER(21);

            GP_WB_WRITE_AK_RX_EARLY_CH_CHANGE_AFTER_VAL_FAIL_EN(0);

            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(1);

            GP_WB_WRITE_AK_RX_RSSI_CLEAR_ON_LR_CYC_DET(1);

            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_BLE_TIMEOUT(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);

            GP_WB_WRITE_AK_RX_BT_CLR_MAG_SR_ON_PIP(0);
            GP_WB_WRITE_AK_RX_BT_LR_RSSI_DET_PSEUDO_DIS_LEN(0);
            GP_WB_WRITE_AK_RX_BT_PIP_PSEUDO_MAKS_ALWAYS_EN(0);
            GP_WB_WRITE_AK_RX_RSSI_HOLD_UPON_TRAINING_RST(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_LONG(255);
            GP_WB_WRITE_AK_RX_BLE_TIMEOUT_VALUE_PIP(255);
            GP_WB_WRITE_AK_RX_BT_LR_RESTART_ON_PIP_EN(0);
            GP_WB_WRITE_AK_RX_LAST_RX_BYTES_LR_LEV(0);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);

            GP_WB_WRITE_AK_RX_BT_FAST_VALIDATION(0);
            GP_WB_WRITE_AK_RX_BT_2M_DIRECT_I_DELAY(0);
            GP_WB_WRITE_AK_RX_BT_2M_VALIDATION_START_TUNE(-1);
            GP_WB_WRITE_AK_RX_BT_IQ_BUFFER_DEPTH_CORR(0);

            GP_WB_WRITE_AK_RX_FAIL_TIMEOUT_VALUE(20);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_BT(203);

            break;
        }
        case RAP_RX_MODE_S_A0:
        case RAP_RX_MODE_S_A1:
        case RAP_RX_MODE_S_DF:
        case RAP_RX_MODE_NS_A0:
        case RAP_RX_MODE_NS_A1:
        case RAP_RX_MODE_NS_DF:
        case RAP_RX_MODE_NS_AD:
        case RAP_RX_MODE_LS_A0:
        case RAP_RX_MODE_LS_A1:
        case RAP_RX_MODE_LS_DF:
        case RAP_RX_MODE_LS_AD:
        case RAP_RX_MODE_MS_A0:
        case RAP_RX_MODE_MS_A1:
        case RAP_RX_MODE_MS_DF:
        case RAP_RX_MODE_MS_AD:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_BLE(GP_WB_ENUM_AK_BLE_RECEIVER_MODE_BLE_HDR);

            GP_WB_WRITE_AK_RX_VALIDATION_PRE_DATA_CHECK_EN(1);

            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE_HDR(0);
            GP_WB_WRITE_AK_RX_BT_2M_LAST_RX_BYTES_LEV(1);
            GP_WB_WRITE_AK_RX_BT_2M_BIAS_GAIN(0);
            GP_WB_WRITE_AK_RX_BT_2M_LP_INIT_STATE_IDX_OVERRULE_EN(1);
            GP_WB_WRITE_AK_RX_SFSK_EN(1);
            GP_WB_WRITE_AK_RX_BT_2M_DATA_VALID_ENABLE(1);
            GP_WB_WRITE_AK_RX_BT_VALIDATION_THRESH(63);
            GP_WB_WRITE_AK_RX_BTS_VALIDATION_N(16);

            GP_WB_WRITE_AK_RX_BT_I_ONLY_EN(0);
            GP_WB_WRITE_AK_RX_BT_I_ONLY_BUF_EN(0);

            GP_WB_WRITE_AK_RX_RSSI_CLEAR_ON_LR_CYC_DET(1);

            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);
            GP_WB_WRITE_AK_RX_BT_PIP_PSEUDO_MAKS_ALWAYS_EN(0);
            GP_WB_WRITE_AK_RX_RSSI_HOLD_UPON_TRAINING_RST(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);

            GP_WB_WRITE_AK_RX_BT_FAST_VALIDATION(0);
            GP_WB_WRITE_AK_RX_BT_2M_DIRECT_I_DELAY(0);
            GP_WB_WRITE_AK_RX_BT_2M_VALIDATION_START_TUNE(-1);
            GP_WB_WRITE_AK_RX_BT_IQ_BUFFER_DEPTH_CORR(0);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_BT(203);

            break;
        }
        case RAP_RX_MODE_MSB_A0:
        case RAP_RX_MODE_MSB_A1:
        case RAP_RX_MODE_MSB_DF:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_BLE(GP_WB_ENUM_AK_BLE_RECEIVER_MODE_BLE);

            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(1);
            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE(1);

            GP_WB_WRITE_AK_RX_BT_LR_MBR_EN(0);
            GP_WB_WRITE_AK_RX_BT_TIMEOUT_QUARD_TIMER(9);
            GP_WB_WRITE_AK_RX_HOLD_BLE_TIMEOUT_COUNTER_EN(0);

            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE_HDR(0);
            GP_WB_WRITE_AK_RX_BT_2M_LAST_RX_BYTES_LEV(1);
            GP_WB_WRITE_AK_RX_BT_2M_BIAS_GAIN(0);
            GP_WB_WRITE_AK_RX_BT_2M_LP_INIT_STATE_IDX_OVERRULE_EN(1);
            GP_WB_WRITE_AK_RX_SFSK_EN(1);
            GP_WB_WRITE_AK_RX_BT_2M_DATA_VALID_ENABLE(1);
            GP_WB_WRITE_AK_RX_BT_VALIDATION_THRESH(63);
            GP_WB_WRITE_AK_RX_BTS_VALIDATION_N(10);

            GP_WB_WRITE_AK_RX_BT_I_ONLY_EN(0);
            GP_WB_WRITE_AK_RX_BT_I_ONLY_BUF_EN(0);

            GP_WB_WRITE_AK_RX_RSSI_CLEAR_ON_LR_CYC_DET(1);

            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_BLE_TIMEOUT(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);
            GP_WB_WRITE_AK_RX_BT_CLR_MAG_SR_ON_PIP(0);
            GP_WB_WRITE_AK_RX_BT_PIP_PSEUDO_MAKS_ALWAYS_EN(0);
            GP_WB_WRITE_AK_RX_RSSI_HOLD_UPON_TRAINING_RST(0);
            GP_WB_WRITE_AK_RX_EARLY_CH_CHANGE_AFTER_VAL_FAIL_EN(1);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);

            GP_WB_WRITE_AK_RX_BT_FAST_VALIDATION(0);
            GP_WB_WRITE_AK_RX_BT_2M_DIRECT_I_DELAY(0);
            GP_WB_WRITE_AK_RX_BT_2M_VALIDATION_START_TUNE(-1);
            GP_WB_WRITE_AK_RX_BT_IQ_BUFFER_DEPTH_CORR(0);

            GP_WB_WRITE_AK_RX_FAIL_TIMEOUT_VALUE(40);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_BT(203);

            break;
        }
        case RAP_RX_MODE_MSBR_A0:
        case RAP_RX_MODE_MSBR_A1:
        case RAP_RX_MODE_MSBR_DF:
        {

            GP_WB_WRITE_AK_PLME_RX_MODE_BLE(GP_WB_ENUM_AK_BLE_RECEIVER_MODE_BLE_CONCURRENT);

            GP_WB_WRITE_AK_RX_RSSI_ALWAYS_VALID_ONLY_AFTER_DET(1);
            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE(1);

            GP_WB_WRITE_AK_RX_BT_LR_MBR_EN(1);
            GP_WB_WRITE_AK_RX_BT_TIMEOUT_QUARD_TIMER(21);
            GP_WB_WRITE_AK_RX_HOLD_BLE_TIMEOUT_COUNTER_EN(1);

            GP_WB_WRITE_AK_RX_RSSI_BASED_BLE_HDR(0);
            GP_WB_WRITE_AK_RX_BT_2M_LAST_RX_BYTES_LEV(1);
            GP_WB_WRITE_AK_RX_BT_2M_BIAS_GAIN(0);
            GP_WB_WRITE_AK_RX_BT_2M_LP_INIT_STATE_IDX_OVERRULE_EN(1);
            GP_WB_WRITE_AK_RX_SFSK_EN(1);
            GP_WB_WRITE_AK_RX_BT_2M_DATA_VALID_ENABLE(1);
            GP_WB_WRITE_AK_RX_BT_VALIDATION_THRESH(63);
            GP_WB_WRITE_AK_RX_BTS_VALIDATION_N(10);

            GP_WB_WRITE_AK_RX_BT_I_ONLY_EN(0);
            GP_WB_WRITE_AK_RX_BT_I_ONLY_BUF_EN(0);

            GP_WB_WRITE_AK_RX_RSSI_CLEAR_ON_LR_CYC_DET(1);

            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_BLE_TIMEOUT(1);
            GP_WB_WRITE_AK_RX_RESTART_CONV_ENGINE_ON_PIP(1);
            GP_WB_WRITE_AK_RX_BT_CLR_MAG_SR_ON_PIP(0);
            GP_WB_WRITE_AK_RX_BT_LR_RSSI_DET_PSEUDO_DIS_LEN(0);
            GP_WB_WRITE_AK_RX_BT_PIP_PSEUDO_MAKS_ALWAYS_EN(0);
            GP_WB_WRITE_AK_RX_RSSI_HOLD_UPON_TRAINING_RST(0);
            GP_WB_WRITE_AK_RX_RSSI_DISABLE_CFG(0);
            GP_WB_WRITE_AK_RX_RSSI_DSP_FORCE_ON(0);
            GP_WB_WRITE_AK_RX_BT_LR_RESTART_ON_PIP_EN(0);
            GP_WB_WRITE_AK_RX_LAST_RX_BYTES_LR_LEV(0);

            GP_WB_WRITE_AK_RX_RSSI_REF_RST_ON_ZB_SFD_DET(1);

            GP_WB_WRITE_AK_RX_BT_FAST_VALIDATION(0);
            GP_WB_WRITE_AK_RX_BT_2M_DIRECT_I_DELAY(0);
            GP_WB_WRITE_AK_RX_BT_2M_VALIDATION_START_TUNE(-1);
            GP_WB_WRITE_AK_RX_BT_IQ_BUFFER_DEPTH_CORR(0);

            GP_WB_WRITE_AK_RX_FAIL_TIMEOUT_VALUE(20);

            GP_WB_WRITE_AK_RX_PREAMBLE_THRESH_BT(203);


            break;
        }
        default:
        {

            break;
        }
    }


}

void ak_rap_rx_antenna_set_mode(UInt8 rx_mode)
{

    switch (rx_mode)
    {


        case RAP_RX_MODE_O_A0:
        case RAP_RX_MODE_N_A0:
        case RAP_RX_MODE_M_A0:
        case RAP_RX_MODE_MB_A0:
        case RAP_RX_MODE_MBR_A0:
        case RAP_RX_MODE_B_A0:
        case RAP_RX_MODE_H_A0:
        case RAP_RX_MODE_R_A0:
        case RAP_RX_MODE_BR_A0:
        case RAP_RX_MODE_NS_A0:
        case RAP_RX_MODE_MS_A0:
        case RAP_RX_MODE_MSB_A0:
        case RAP_RX_MODE_MSBR_A0:
        case RAP_RX_MODE_MBXZB:
        {
            GP_WB_WRITE_AK_RX_ANT_USE_ZB(0);
            GP_WB_WRITE_AK_RX_ANT_USE_BLE(0);
            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_RX_USE_DUAL_PATH(0);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RADIOITF_RX1_RXFE_CTRL(1);


            break;
        }
        case RAP_RX_MODE_O_A1:
        case RAP_RX_MODE_N_A1:
        case RAP_RX_MODE_M_A1:
        case RAP_RX_MODE_MB_A1:
        case RAP_RX_MODE_MBR_A1:
        case RAP_RX_MODE_B_A1:
        case RAP_RX_MODE_H_A1:
        case RAP_RX_MODE_NS_A1:
        case RAP_RX_MODE_MS_A1:
        case RAP_RX_MODE_MSB_A1:
        case RAP_RX_MODE_MSBR_A1:
        case RAP_RX_MODE_R_A1:
        case RAP_RX_MODE_BR_A1:
        {
            GP_WB_WRITE_AK_RX_ANT_USE_ZB(1);
            GP_WB_WRITE_AK_RX_ANT_USE_BLE(1);
            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_RX_USE_DUAL_PATH(0);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RADIOITF_RX1_RXFE_CTRL(1);


            break;
        }
        case RAP_RX_MODE_O_DF:
        case RAP_RX_MODE_N_DF:
        case RAP_RX_MODE_M_DF:
        case RAP_RX_MODE_MB_DF:
        case RAP_RX_MODE_MBR_DF:
        case RAP_RX_MODE_B_DF:
        case RAP_RX_MODE_H_DF:
        case RAP_RX_MODE_NS_DF:
        case RAP_RX_MODE_MS_DF:
        case RAP_RX_MODE_MSB_DF:
        case RAP_RX_MODE_MSBR_DF:
        case RAP_RX_MODE_R_DF:
        case RAP_RX_MODE_BR_DF:
        {
            GP_WB_WRITE_AK_RX_ANT_USE_ZB(0);
            GP_WB_WRITE_AK_RX_ANT_USE_BLE(0);
            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_RX_USE_DUAL_PATH(0);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(3);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(3);
            GP_WB_WRITE_AK_RADIOITF_RFDET0_0(2);
            GP_WB_WRITE_AK_RADIOITF_RFDET0_1(2);
            GP_WB_WRITE_AK_RADIOITF_RX1_RXFE_CTRL(0);

            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);

            GP_WB_WRITE_AK_RX_SIGC1_FORCE_OFF(1);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RX_DIFF_COMBINER_ENA(1);
            GP_WB_WRITE_AK_RX_ROTATE_QUAD(2);
            GP_WB_WRITE_AK_RX_ROTATE_ANGLE(1);
            GP_WB_WRITE_AK_RX_ROTATE_POSITIVE(0);


            break;
        }
        case RAP_RX_MODE_L_A0:
        case RAP_RX_MODE_LS_A0:
        {
            GP_WB_WRITE_AK_RX_ANT_USE_ZB(0);
            GP_WB_WRITE_AK_RX_ANT_USE_BLE(0);
            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_DC_STOP_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_DC_A0);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_RX_USE_DUAL_PATH(0);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RADIOITF_RX1_RXFE_CTRL(1);


            break;
        }
        case RAP_RX_MODE_L_A1:
        case RAP_RX_MODE_LS_A1:
        {
            GP_WB_WRITE_AK_RX_ANT_USE_ZB(1);
            GP_WB_WRITE_AK_RX_ANT_USE_BLE(1);
            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_PLME_DC_STOP_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_DC_A1);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A0);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_A1);
            GP_WB_WRITE_AK_RX_USE_DUAL_PATH(0);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RADIOITF_RX1_RXFE_CTRL(1);


            break;
        }
        case RAP_RX_MODE_L_DF:
        case RAP_RX_MODE_LS_DF:
        {
            GP_WB_WRITE_AK_RX_ANT_USE_ZB(0);
            GP_WB_WRITE_AK_RX_ANT_USE_BLE(0);
            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_PLME_DC_STOP_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_DC_DF);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_DF);
            GP_WB_WRITE_AK_RX_USE_DUAL_PATH(0);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(3);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(3);
            GP_WB_WRITE_AK_RADIOITF_RFDET0_0(2);
            GP_WB_WRITE_AK_RADIOITF_RFDET0_1(2);
            GP_WB_WRITE_AK_RADIOITF_RX1_RXFE_CTRL(0);


            break;
        }
        case RAP_RX_MODE_B_AD:
        case RAP_RX_MODE_H_AD:
        case RAP_RX_MODE_R_AD:
        case RAP_RX_MODE_BR_AD:
        {
            GP_WB_WRITE_AK_RX_ANT_USE_ZB(0);
            GP_WB_WRITE_AK_RX_ANT_USE_BLE(0);
            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_RX_USE_DUAL_PATH(1);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RADIOITF_RX1_RXFE_CTRL(1);


            break;
        }
        case RAP_RX_MODE_O_AD:
        case RAP_RX_MODE_N_AD:
        case RAP_RX_MODE_M_AD:
        case RAP_RX_MODE_NS_AD:
        case RAP_RX_MODE_MS_AD:
        {
            GP_WB_WRITE_AK_RX_ANT_USE_ZB(0);
            GP_WB_WRITE_AK_RX_ANT_USE_BLE(0);
            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_RX_USE_DUAL_PATH(1);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RADIOITF_RX1_RXFE_CTRL(1);


            break;
        }
        case RAP_RX_MODE_L_AD:
        case RAP_RX_MODE_LS_AD:
        {
            GP_WB_WRITE_AK_RX_ANT_USE_ZB(0);
            GP_WB_WRITE_AK_RX_ANT_USE_BLE(0);
            GP_WB_WRITE_AK_PLME_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TX_TO_RX_STATE_CHANGE_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_DC_STOP_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_TRAINING_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_DC_AD);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_0_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_PLME_TO_DATAPHASE_1_TRANSITION(GP_WB_ENUM_AK_PHY_STATE_TRANSITION_TO_RX_AD);
            GP_WB_WRITE_AK_RX_USE_DUAL_PATH(1);
            GP_WB_WRITE_AK_RX_RX0_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RX_RX1_RXFE_IIR_PATH_SEL_1(1);
            GP_WB_WRITE_AK_RADIOITF_RX1_RXFE_CTRL(1);


            break;
        }
        default:
        {

            break;
        }
    }

    switch (rx_mode)
    {
        case RAP_RX_MODE_R_AD:
        case RAP_RX_MODE_BR_AD:
        {
            GP_WB_WRITE_AK_RX_EN_PIP_FOR_BLE(0);
            break;
        }
        default:
        {
            GP_WB_WRITE_AK_RX_EN_PIP_FOR_BLE(1);
            break;
        }
    }

}

void ak_rap_rx_set_mode(UInt8 rx_mode)
{
    ak_rap_rx_zb_set_mode(rx_mode);
    ak_rap_rx_ble_set_mode(rx_mode);
    ak_rap_rx_antenna_set_mode(rx_mode);
}

UInt8 ak_rap_rx_get_rx_on_when_idle(void)
{
    UInt8 rx_on_when_idle = 0;
    rx_on_when_idle = GP_WB_READ_AK_RTM_TRC_RX_ON_WHEN_IDLE_CH();
    return rx_on_when_idle;
}

void ak_rap_rx_set_rx_on_when_idle(UInt8 rx_on_mask)
{
    ak_rap_rt_ipc_cmd(GP_WB_ENUM_AK_RT_CMD_TYPE_RX_ON_WHEN_IDLE_SET, rx_on_mask);
}

void ak_rap_rx_set_rx_on_when_idle_chidx(UInt8 chidx, Bool rx_on)
{
    UInt8 rx_on_int;
    rx_on_int = rx_on;
    ak_rap_rt_ipc_cmd(GP_WB_ENUM_AK_RT_CMD_TYPE_RX_ON_WHEN_IDLE_SET_CHIDX, chidx + (rx_on_int<<8));
}

Int8 ak_rap_rx_rssi_to_dbm(UInt8 rssi)
{
    return (rssi / 2) - 124;
}

UInt8 ak_rap_rx_dbm_to_rssi(Int8 dbm)
{
    if (dbm < -124)
    {
        return 0;
    }
    if (dbm > 3)
    {
        return 255;
    }
    return 2 * (dbm + 124);
}

